class CarInfo {
  static List<CarModelBrand> carModelBrands = [
    CarModelBrand(
      brand: "Audi",
      models: ["80", "A1", "A3", "A4", "A5", "A6", "A7", "A8", "e-tron", "E-tron GT", "Q2", "Q3", "Q5", "Q7", "Q8", "S8", "TT"],
    ),
    CarModelBrand(
      brand: "BMW",
      models: [
        "116i",
        "218i",
        "318i",
        "320i",
        "325i",
        "328i",
        "330i",
        "420i",
        "428i",
        "430i",
        "520i",
        "523i",
        "525i",
        "528i",
        "530i",
        "535 GT",
        "640i",
        "645i",
        "650i",
        "730Li",
        "740Li",
        "750Li",
        "760Li",
        "i8",
        "M4",
        "X1",
        "X2",
        "X3",
        "X4",
        "X5",
        "X6",
        "X7",
        "Z4"
      ],
    ),
    CarModelBrand(
      brand: "Ford",
      models: ["Aspire", "EcoSport", "Escape", "Everest", "Explorer", "F 150", "Fiesta", "Focus", "Laser", "Mondeo", "Mustang", "Ranger", "Ranger Raptor", "Territory", "Tourneo", "Transit"],
    ),
    CarModelBrand(
      brand: "Honda",
      models: ["Accord", "Brio", "City", "Civic", "CR-V", "HR-V", "Jazz", "Odyssey", "Pilot"],
    ),
    CarModelBrand(
      brand: "Huyndai",
      models: [
        "Accent",
        "Avante",
        "Azera",
        "Click",
        "County",
        "Creta",
        "Elantra",
        "Eon",
        "Equus",
        "Genesis",
        "Getz",
        "Grand i10",
        "Grand Starex",
        "HD",
        "i10",
        "i20",
        "i20 Active",
        "i30",
        "Kona",
        "Lantra",
        "Mighty",
        "Mighty EX8 GT",
        "Porter",
        "Santa FE",
        "Solati",
        "Sonata",
        "Starex",
        "Stargazer",
        "Terracan",
        "Tucson",
        "Universe",
        "Veloster",
        "Veracruz",
        "Verna",
        "XG",
      ],
    ),
    CarModelBrand(brand: "Kia", models: [
      "Bongo",
      "Carens",
      "Carnival",
      "CD5",
      "Cerato",
      "Cerato Koup",
      "Forte",
      "Frontier",
      "Jeep",
      "K",
      "K125",
      "K140",
      "K165",
      "K190",
      "K200",
      "K250",
      "K250L",
      "K2700",
      "K3",
      "K3000S",
      "K5",
      "Morning",
      "Optima",
      "Picanto",
      "Pride",
      "Rhino",
      "Rio",
      "Rondo",
      "Sedona",
      "Seltos",
      "Soluto",
      "Sonet",
      "Sorento",
      "Soul",
      "Spectra",
      "Sportage"
    ]),
    CarModelBrand(brand: "Lexus", models: [
      "CT 200",
      "ES 250",
      "ES 300",
      "ES 350",
      "GS 300",
      "GS 350",
      "GS 430",
      "GX 460",
      "GX 470",
      "IS 250",
      "IS 300",
      "LC 500",
      "LM 300",
      "LM 350",
      "LS 400",
      "LS 430",
      "LS 460",
      "LX 470",
      "LX 570",
      "LX 600",
      "NX 200T",
      "NX 300",
      "RX 200",
      "RX 300",
      "RX 330",
      "RX 350",
      "RX 450"
    ]),
    CarModelBrand(brand: "Mazda", models: ["2", "3", "323", "5", "6", "626", "929", "BT-50", "CX-3", "CX-30", "CX-5", "CX-8", "CX-9", "Premacy", "Tribute"]),
    CarModelBrand(brand: "Mercedes-Benz", models: [
      "A200",
      "A250",
      "AMG GT 53",
      "C 230",
      "C 240",
      "C 250",
      "C180",
      "C200",
      "C280",
      "C300",
      "C43",
      "CLA 200",
      "CLA 250",
      "CLA 45",
      "CLA 45 AMG",
      "CLS 500",
      "E180",
      "E200",
      "E200K",
      "E240",
      "E250",
      "E280",
      "E300",
      "E350",
      "E400",
      "G63",
      "GL 320",
      "GL 350",
      "GL 450",
      "GL 550",
      "GLA 200",
      "GLA 250",
      "GLA 45",
      "GLA 45S",
      "GLB 35",
      "GLC",
      "GLC 250",
      "GLC 300",
      "GLC 400",
      "GLE 43",
      "GLE 450"
    ]),
    CarModelBrand(brand: "Mitsubishi", models: [
      "3000GT",
      "Attrage",
      "Canter",
      "Chariot",
      "EK wagon",
      "Fuso",
      "Galant",
      "Grandis",
      "Jolie",
      "Lancer",
      "Lancer Fortis",
      "Mirage",
      "Outlander",
      "Outlander Sport",
      "Pajero",
      "Pajero Sport",
      "Triton",
      "XFC Concept",
      "Xpander",
      "Xpander Cross",
      "Zinger"
    ]),
    CarModelBrand(brand: "Nissan", models: [
      "Almera",
      "Altima",
      "Bluebird",
      "Cedric",
      'Cefiro',
      "Grand livina",
      "Juke",
      "Kicks",
      "Maxima",
      "Murano",
      "Navara",
      "Pixo",
      "Prairie",
      "Qashqai",
      "Sunny",
      "Teana",
      "Terra",
      "Terrano",
      "Tiida",
      "X Terra",
      "X trail"
    ]),
    CarModelBrand(brand: "Toyota", models: [
      "4 Runner",
      "86",
      "Alphard",
      "Avalon",
      "Avanza",
      "Avanza Premio",
      "Aygo",
      "Camry",
      "Celica",
      "Corolla",
      "Crorolla Cross",
      "Corola Altis",
      "Corona",
      "Cressida",
      "Crown",
      "Fj cruiser",
      "Fortuner",
      "FT 86",
      "Hiace",
      "Highlander",
      "Hilux",
      "Innova",
      "Land Cruiser",
      "Land Cruiser Prado",
      "Previa",
      "Raize",
      "RAV4",
      "Rush",
      "Sienna",
      "Veloz",
      "Veloz Cross",
      "Venza",
      "Vios",
      "Wigo",
      "Wish",
      "Yaris",
      "Zace"
    ]),
    CarModelBrand(brand: "VinFast", models: ["Fadill", "LUX A2.0", "LUX SA2.0", "VF e34", "VF5", "VF58", "VF9"]),
    CarModelBrand(brand: "Acura", models: ["MDX", "ZDX"]),
    CarModelBrand(brand: "Aston Martin", models: ["DBX", "DB11"]),
    CarModelBrand(brand: "BAIC", models: ["Beijinh X7", "Q7"]),
    CarModelBrand(brand: "Bentley", models: ["Bentayga", "Continental", "Flying Spur", "Mulsanne"]),
    CarModelBrand(brand: "BYD", models: ["F0"]),
    CarModelBrand(brand: "Cadillac", models: ["Escalade"]),
    CarModelBrand(brand: "Camc", models: ["H9"]),
    CarModelBrand(brand: "Chenglong", models: ["M3"]),
    CarModelBrand(brand: "Chery", models: ["QQ3"]),
    CarModelBrand(brand: "Chevrolet", models: ["Aveo", "Camaro", "Captiva", "Colorado", "Cruze", "Laceti", "Matiz", "Orlando", "Spark", "Trailblazer", "Trax", "Vivant"]),
    CarModelBrand(brand: "Chiến Thắng", models: ["Kendo", "Xe Ben"]),
    CarModelBrand(brand: "Chrysler", models: ["300", "300C"]),
    CarModelBrand(brand: "Daehan", models: ["Tera 345SL"]),
    CarModelBrand(brand: "Daewoo", models: ["Bus", "Cielo", "Damas", "Gentra", "GentraX", "Lacetti", "Lanos", "Leganza", "Magnus", "Matiz", "Novus", "Nubira"]),
    CarModelBrand(brand: "Daihatsu", models: ["Citivan", "Terios"]),
    CarModelBrand(brand: "Đô Thành", models: ["IZ65"]),
    CarModelBrand(brand: "Dodge", models: ["Challenger"]),
    CarModelBrand(brand: "Dongfeng", models: ["K9", "T30", "X30"]),
    CarModelBrand(brand: "FAW", models: ["Tiger", "Xe Tải Thùng"]),
    CarModelBrand(brand: "Ferrari", models: ["488", "SF90"]),
    CarModelBrand(brand: "Fiat", models: ["500", "Albea", "Doblo", "Siena", "Tempra"]),
    CarModelBrand(brand: "Foton", models: ["Auman", "Gratour", "Ollin"]),
    CarModelBrand(brand: "Gaz", models: ["Gazelle Next Van"]),
    CarModelBrand(brand: "Geely", models: ["Emgrand EC 718"]),
    CarModelBrand(brand: "Genesis", models: ["G90"]),
    CarModelBrand(brand: "Haima", models: ["2", "Freema"]),
    CarModelBrand(brand: "Hino", models: ["300 Series", "FL"]),
    CarModelBrand(brand: "Hoa Mai", models: ["Xe tải ben"]),
    CarModelBrand(brand: "Howo", models: ["Sitrak", "TX", "Xe ben"]),
    CarModelBrand(brand: "Infiniti", models: ["QX60"]),
    CarModelBrand(brand: "Isuzu", models: ["D-MAX", "FRR", "F-SERIES", "FVM", "FVM1500", "FVR900", "Hi Lander", "mu-X", "NPR", "QKR", "Q-SERIES", "Soyat", "Trooper", "VM"]),
    CarModelBrand(brand: "JAC", models: ["L240", "N200S", "N350S", "N500", "N650 Plus", "N680", "N900", "X99"]),
    CarModelBrand(brand: "Jaguar", models: ["F-Type", "F-Pace", "xe", "XF", "XJ", "XJL"]),
    CarModelBrand(brand: "Jeep", models: ["A2", "Wrangler"]),
    CarModelBrand(brand: "Lamborghini", models: ["aventador", "Huracan", "Urus"]),
    CarModelBrand(brand: "Land Rover", models: [
      "Defender",
      "Defender 110",
      "Defender 90",
      "Discovery",
      "Discovery Sport",
      "Freelander",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
    ]),
    CarModelBrand(brand: "Lifan", models: ["520"]),
    CarModelBrand(brand: "Lincoln", models: ["MKC", "Navigator"]),
    CarModelBrand(brand: "Luxgen", models: ["M7", "S5", "U6", "U7"]),
    CarModelBrand(brand: "Maserati", models: ["Ghibli", "Levante"]),
    CarModelBrand(brand: "McLaren", models: ["570", "650s"]),
    CarModelBrand(brand: "Mekong", models: ["Pronto", "Star"]),
    CarModelBrand(brand: "Mercerdes-AMG", models: ["G 63", "GLB 35", "GLE 53", "GT 53"]),
    CarModelBrand(brand: "Mercerdes-Maybach", models: ["GLS 480", "GLS 600", "S 400", "S 450", "S580", "S 680", "S500"]),
    CarModelBrand(brand: "MG", models: ["5", "HS", "ZS"]),
    CarModelBrand(brand: "Mini", models: ["Clubman", "Cooper", "Cooper S", "John Cooper Works", "One"]),
    CarModelBrand(brand: "Peugeot", models: ["2008", "208", "3008", "405", "408", "5008", "508", "Traveller"]),
    CarModelBrand(brand: "Porsche", models: ["718", "911", "Cayenne", "Cayenne S", "Macan", "Panamera", "Taycan"]),
    CarModelBrand(brand: "Proton", models: ["Wira"]),
    CarModelBrand(brand: "Renault", models: ["Duster", "Sandero Stepway"]),
    CarModelBrand(brand: "Rolls-Royce", models: ["Cullinan", "Ghost", "Phantom"]),
    CarModelBrand(brand: "Samco", models: ["Felix"]),
    CarModelBrand(brand: "Samsung", models: ["QM5"]),
    CarModelBrand(brand: "Ssangyong", models: ["Actyon", "Korando", "Kyron", "Musso", "Rexton II", "Stavic", "TiVoLi"]),
    CarModelBrand(brand: "Subaru", models: ["BRZ", "Forester", "Outback"]),
    CarModelBrand(brand: "Suzuki", models: [
      "Alto",
      "APV",
      "Blind Van",
      "Carry",
      "Celerio",
      "Ciaz",
      "Ertiga",
      "Grand vitara",
      "SJ",
      "Super Carry Pro",
      "Super Carry Truck",
      "Super Carry Van",
      "Swift",
      "Vitara",
      "Wagon R",
      "Wagon R+",
      "XL7"
    ]),
    CarModelBrand(brand: "SYM", models: ["V5"]),
    CarModelBrand(brand: "Tata", models: ["Super ACE"]),
    CarModelBrand(brand: "Teraco", models: ["Tera 100", "Tera 180", "Tera 345SL", "Tera 350"]),
    CarModelBrand(brand: "Thaco", models: ["FORLAND", "FRONTIER", "Iveco Daily", "Iveco Daily Plus", "Kia", "OLLIN", "TB85S", "TOWNER"]),
    CarModelBrand(brand: "TMT", models: ["3-5 Tấn", "Daisaki"]),
    CarModelBrand(brand: "Tobe", models: ["Mcar"]),
    CarModelBrand(brand: "UD", models: ["Quester"]),
    CarModelBrand(brand: "Veam", models: ["VPT880", "VPT950", "VT201", "VT260", "VT340", "VT751"]),
    CarModelBrand(brand: "Vinaxuki", models: ["1490T", "1980T"]),
    CarModelBrand(brand: "VM", models: ["NK Series"]),
    CarModelBrand(brand: "Volkswagen", models: ["Beetle", "Jetta", "Passat", "Polo", "T-Cross", "Teramont", "Tiguan", "Tiguan Allspace", "Touareg"]),
    CarModelBrand(brand: "Volvo", models: ["S60", "S90", "S90L", "V60", "V90", "XC40", "XC60", 'XC90']),
    CarModelBrand(brand: "Zotye", models: ["Z8"]),
  ];

  static List<String> years = [
    "1994",
    "1995",
    "1996",
    "1997",
    "1998",
    "1999",
    "2000",
    "2001",
    "2002",
    "2003",
    "2004",
    "2005",
    "2006",
    "2007",
    "2008",
    "2009",
    "2010",
    "2011",
    "2012",
    "2013",
    "2014",
    "2015",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
  ];

  static List<String> colors = [
    "Trắng",
    "Đen",
    "Bạc",
    "Xám",
    "Đỏ",
    "Xanh nước biển",
    "Vàng",
    "Tím",
    "Xanh lá",
    "Hồng",
  ];

  static List<String> numbersOfSeat = [
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ];
}

class CarModelBrand {
  String? brand;
  List<String>? models;

  CarModelBrand({this.brand, this.models});
}
