# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug-sod_user' => :debug,
  'Profile-sod_user' => :release,
  'Release-sod_user' => :release,
  'Debug-sob_express' => :debug,
  'Profile-sob_express' => :release,
  'Release-sob_express' => :release,
  'Debug-suc365_user' => :debug,
  'Profile-suc365_user' => :release,
  'Release-suc365_user' => :release,
  'Debug-g47_user' => :debug,
  'Profile-g47_user' => :release,
  'Release-g47_user' => :release,
  'Debug-appvietsob_user' => :debug,
  'Profile-appvietsob_user' => :release,
  'Release-appvietsob_user' => :release,
  'Debug-vasone' => :debug,
  'Profile-vasone' => :release,
  'Release-vasone' => :release,
  'Debug-fasthub_user' => :debug,
  'Profile-fasthub_user' => :release,
  'Release-fasthub_user' => :release,
  'Debug-goingship' => :debug,
  'Profile-goingship' => :release,
  'Release-goingship' => :release,
  'Debug-grabxanh' => :debug,
  'Profile-grabxanh' => :release,
  'Release-grabxanh' => :release,
  'Debug-inux' => :debug,
  'Profile-inux' => :release,
  'Release-inux' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  # Override Firebase SDK Version
  $FirebaseSDKVersion = '10.22.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  #target 'RunnerTests' do
    #inherit! :search_paths
  #end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',
        'PERMISSION_MICROPHONE=1',
        'PERMISSION_PHOTOS=1',
        'PERMISSION_LOCATION=1',
        'PERMISSION_NOTIFICATIONS=1',
      ]
    end
  end

  # config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
  end

  # Thêm phần xử lý cho BoringSSL-GRPC
  installer.pods_project.targets.each do |target|
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end
